# Generated by Django 5.1.6 on 2025-02-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='published_date',
        ),
    ]
